spring.application.name=ticketService
# H2 Database
spring.datasource.url=jdbc:h2:file:~/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Logging
logging.level.root=INFO
logging.level.com.example.market=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.io.github.resilience4j.retry=DEBUG

resilience4j.retry.instances.buyTickets.max-attempts=3
resilience4j.retry.instances.buyTickets.wait-duration=100ms
resilience4j.retry.instances.buyTickets.enable-exponential-backoff=true
resilience4j.retry.instances.buyTickets.exponential-backoff-multiplier=2
resilience4j.retry.instances.buyTickets.retry-exceptions=java.lang.RuntimeException
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2
resilience4j.timelimiter.time-limiter-aspect-order=3
